apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: apache_php-deployment
spec:
  selector:
    matchLabels:
      app: apache_php
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: apache_php
    spec:
      containers:
      - name: apache_php
        image: ferred/lap_shippingchallenge
        ports:
        - containerPort: 8000

