apiVersion: v1
kind: Service
metadata:
  name: shippingchallenge
  labels:
    app: shippingchallenge
spec:
  selector:
    type: NodePort
    app: shippingchallenge-deployment
  ports:
    - name: apache-php
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 20100
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 20200