apiVersion: v1
kind: Service
metadata:
  name: shippingchallenge
spec:
  selector:
    app: shippingchallenge
  ports:
    - name: apache-php
      protocol: TCP
      port: 80
      targetPort: 8000
      NodePort: 20100
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
      NodePort: 20200