apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: shippingchallenge-deployment
spec:
  selector:
    matchLabels:
      app: shippingchallenge
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: shippingchallenge
    spec:
     containers:
     - name: apache-php
       image: ferred/lap_shippingchallenge
       ports:
       - containerPort: 8000
     - name: postgresql
       image: ferred/postgres_shippingchallenge
       ports:
       - containerPort: 5432

