apiVersion: v1
kind: Service
metadata:
  name: shippingchallenge-service
  labels:
    app: shippingchallenge-service
spec:
  type: LoadBalancer
  selector:
    app: shippingchallenge-deployment
  ports:
    - name: php-apache
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30100
    - name: databasepgsql
      port: 5432
      targetPort: 5432
      nodePort: 30200